# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/govindchari/Desktop/git/nova/nsim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/govindchari/Desktop/git/nova/nsim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/Applications/CMake.app/Contents/bin/cpack --config ./CPackSourceConfig.cmake /Users/govindchari/Desktop/git/nova/nsim/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/Applications/CMake.app/Contents/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/govindchari/Desktop/git/nova/nsim/CMakeFiles /Users/govindchari/Desktop/git/nova/nsim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/govindchari/Desktop/git/nova/nsim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nsim

# Build rule for target.
nsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nsim
.PHONY : nsim

# fast build rule for target.
nsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/build
.PHONY : nsim/fast

src/gnc/AttitudeController.o: src/gnc/AttitudeController.cpp.o
.PHONY : src/gnc/AttitudeController.o

# target to build an object file
src/gnc/AttitudeController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/AttitudeController.cpp.o
.PHONY : src/gnc/AttitudeController.cpp.o

src/gnc/AttitudeController.i: src/gnc/AttitudeController.cpp.i
.PHONY : src/gnc/AttitudeController.i

# target to preprocess a source file
src/gnc/AttitudeController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/AttitudeController.cpp.i
.PHONY : src/gnc/AttitudeController.cpp.i

src/gnc/AttitudeController.s: src/gnc/AttitudeController.cpp.s
.PHONY : src/gnc/AttitudeController.s

# target to generate assembly for a file
src/gnc/AttitudeController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/AttitudeController.cpp.s
.PHONY : src/gnc/AttitudeController.cpp.s

src/gnc/PositionController.o: src/gnc/PositionController.cpp.o
.PHONY : src/gnc/PositionController.o

# target to build an object file
src/gnc/PositionController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/PositionController.cpp.o
.PHONY : src/gnc/PositionController.cpp.o

src/gnc/PositionController.i: src/gnc/PositionController.cpp.i
.PHONY : src/gnc/PositionController.i

# target to preprocess a source file
src/gnc/PositionController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/PositionController.cpp.i
.PHONY : src/gnc/PositionController.cpp.i

src/gnc/PositionController.s: src/gnc/PositionController.cpp.s
.PHONY : src/gnc/PositionController.s

# target to generate assembly for a file
src/gnc/PositionController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/PositionController.cpp.s
.PHONY : src/gnc/PositionController.cpp.s

src/gnc/ThrustAllocator.o: src/gnc/ThrustAllocator.cpp.o
.PHONY : src/gnc/ThrustAllocator.o

# target to build an object file
src/gnc/ThrustAllocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/ThrustAllocator.cpp.o
.PHONY : src/gnc/ThrustAllocator.cpp.o

src/gnc/ThrustAllocator.i: src/gnc/ThrustAllocator.cpp.i
.PHONY : src/gnc/ThrustAllocator.i

# target to preprocess a source file
src/gnc/ThrustAllocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/ThrustAllocator.cpp.i
.PHONY : src/gnc/ThrustAllocator.cpp.i

src/gnc/ThrustAllocator.s: src/gnc/ThrustAllocator.cpp.s
.PHONY : src/gnc/ThrustAllocator.s

# target to generate assembly for a file
src/gnc/ThrustAllocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/gnc/ThrustAllocator.cpp.s
.PHONY : src/gnc/ThrustAllocator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nsim/GenerateForcesMoments.o: src/nsim/GenerateForcesMoments.cpp.o
.PHONY : src/nsim/GenerateForcesMoments.o

# target to build an object file
src/nsim/GenerateForcesMoments.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/GenerateForcesMoments.cpp.o
.PHONY : src/nsim/GenerateForcesMoments.cpp.o

src/nsim/GenerateForcesMoments.i: src/nsim/GenerateForcesMoments.cpp.i
.PHONY : src/nsim/GenerateForcesMoments.i

# target to preprocess a source file
src/nsim/GenerateForcesMoments.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/GenerateForcesMoments.cpp.i
.PHONY : src/nsim/GenerateForcesMoments.cpp.i

src/nsim/GenerateForcesMoments.s: src/nsim/GenerateForcesMoments.cpp.s
.PHONY : src/nsim/GenerateForcesMoments.s

# target to generate assembly for a file
src/nsim/GenerateForcesMoments.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/GenerateForcesMoments.cpp.s
.PHONY : src/nsim/GenerateForcesMoments.cpp.s

src/nsim/SaveData.o: src/nsim/SaveData.cpp.o
.PHONY : src/nsim/SaveData.o

# target to build an object file
src/nsim/SaveData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/SaveData.cpp.o
.PHONY : src/nsim/SaveData.cpp.o

src/nsim/SaveData.i: src/nsim/SaveData.cpp.i
.PHONY : src/nsim/SaveData.i

# target to preprocess a source file
src/nsim/SaveData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/SaveData.cpp.i
.PHONY : src/nsim/SaveData.cpp.i

src/nsim/SaveData.s: src/nsim/SaveData.cpp.s
.PHONY : src/nsim/SaveData.s

# target to generate assembly for a file
src/nsim/SaveData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/SaveData.cpp.s
.PHONY : src/nsim/SaveData.cpp.s

src/nsim/simulations/run6DOF.o: src/nsim/simulations/run6DOF.cpp.o
.PHONY : src/nsim/simulations/run6DOF.o

# target to build an object file
src/nsim/simulations/run6DOF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/simulations/run6DOF.cpp.o
.PHONY : src/nsim/simulations/run6DOF.cpp.o

src/nsim/simulations/run6DOF.i: src/nsim/simulations/run6DOF.cpp.i
.PHONY : src/nsim/simulations/run6DOF.i

# target to preprocess a source file
src/nsim/simulations/run6DOF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/simulations/run6DOF.cpp.i
.PHONY : src/nsim/simulations/run6DOF.cpp.i

src/nsim/simulations/run6DOF.s: src/nsim/simulations/run6DOF.cpp.s
.PHONY : src/nsim/simulations/run6DOF.s

# target to generate assembly for a file
src/nsim/simulations/run6DOF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nsim.dir/build.make CMakeFiles/nsim.dir/src/nsim/simulations/run6DOF.cpp.s
.PHONY : src/nsim/simulations/run6DOF.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... nsim"
	@echo "... src/gnc/AttitudeController.o"
	@echo "... src/gnc/AttitudeController.i"
	@echo "... src/gnc/AttitudeController.s"
	@echo "... src/gnc/PositionController.o"
	@echo "... src/gnc/PositionController.i"
	@echo "... src/gnc/PositionController.s"
	@echo "... src/gnc/ThrustAllocator.o"
	@echo "... src/gnc/ThrustAllocator.i"
	@echo "... src/gnc/ThrustAllocator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nsim/GenerateForcesMoments.o"
	@echo "... src/nsim/GenerateForcesMoments.i"
	@echo "... src/nsim/GenerateForcesMoments.s"
	@echo "... src/nsim/SaveData.o"
	@echo "... src/nsim/SaveData.i"
	@echo "... src/nsim/SaveData.s"
	@echo "... src/nsim/simulations/run6DOF.o"
	@echo "... src/nsim/simulations/run6DOF.i"
	@echo "... src/nsim/simulations/run6DOF.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

